/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioGenerator: typeof import('./components/AudioGenerator.vue')['default']
    AudioGeneratorV2: typeof import('./components/AudioGeneratorV2.vue')['default']
    AudioPlayerBtn: typeof import('./components/AudioPlayerBtn.vue')['default']
    MakerAudios: typeof import('./components/MakerAudios.vue')['default']
    MakerAudiosDialog: typeof import('./components/MakerAudiosDialog.vue')['default']
    MakerAudiosDialogInput: typeof import('./components/MakerAudiosDialogInput.vue')['default']
    MakerAudiosDialogInputV2: typeof import('./components/MakerAudiosDialogInputV2.vue')['default']
    MakerAudiosDialogV2: typeof import('./components/MakerAudiosDialogV2.vue')['default']
    MakerAudiosList: typeof import('./components/MakerAudiosList.vue')['default']
    MakerAudiosListV2: typeof import('./components/MakerAudiosListV2.vue')['default']
    MakerAudiosV2: typeof import('./components/MakerAudiosV2.vue')['default']
    MakerChat: typeof import('./components/MakerChat.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    VoiceView: typeof import('./components/VoiceView.vue')['default']
    VoiceViewV2: typeof import('./components/VoiceViewV2.vue')['default']
  }
}
